import { NextRequest, NextResponse } from "next/server";

import {Event, IEvent} from "@/database";
import dbConnect from "@/lib/mongodb";

/** Matches the URL-friendly slugs generated by the Event pre-save hook. */
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

type EventSlugParams = Promise<{ slug: string }>;

function jsonError(message: string, status: number) {
  return NextResponse.json({ message }, { status });
}

export async function GET(
  _request: NextRequest,
  { params }: { params: EventSlugParams },
) {
  try {
    const { slug: rawSlug } = await params;
    const slug = rawSlug.trim().toLowerCase();

    if (!slug) {
      return jsonError("Event slug is required", 400);
    }

    if (!SLUG_PATTERN.test(slug)) {
      return jsonError("Invalid event slug", 400);
    }

    await dbConnect();

    const event: IEvent | null = await Event.findOne({ slug });

    if (!event) {
      return jsonError("Event not found", 404);
    }

    return NextResponse.json({ message: "Event loaded", event }, { status: 200 });

  } catch (err) {
    console.error(err);
    return NextResponse.json(
      {
        message: "Failed to get event",
        error: err instanceof Error ? err.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
